load Fields .

fmod STORAGE{Field :: TRIV} is
    pr FIELDS{Field} .

    sort Struct .

    subsort Struct < Value .

    op mtSt : -> Struct .
    op store : Value Field$Elt Value -> Value .
    op select : Value Field$Elt -> Value .
    op find : Value List{Field} -> Value .

    var st : Struct .
    var fld : Field$Elt .
    var val : Value .
    var flds : List{Field} .

    eq find(val, nil) = val .
    eq find(store(st, fld, val), fld flds) = find(val, flds) .
endfm
