red read(defaultMap, k1) == defaultValue .

red read(write(defaultMap, k1, v1), k1) == v1 .

red read(write(emptyMap, k1, v1), k1) == v1 .

red read(write(defaultMap, k1, v1), k2) == defaultValue .

red read(write(write(defaultMap, k1, v1), k1, v2), k1) == v2 .

red read(write(write(emptyMap, k1, v1), k1, v2), k1) == v2 .

red read(write(write(defaultMap, k1, v1), k1, v2), k2) == defaultValue .

red write(write(defaultMap, k1, v1), k1, v2) .

red read(emptyMap, k1) .
