load Fields .

fmod STORAGE{Field :: TRIV} is
    pr FIELDS{Field} .

    sort Struct .

    subsort Struct < StValue .   *** structHeader.key: Struct \extends StValue

    *** signatures mirror SolKey structRules.key: storage holds StValue
    op mtSt : -> Struct .
    op storeSt : Struct Field$Elt StValue -> Struct .
    op selectSt : Struct Field$Elt -> StValue .
    op find : Struct List{Field} -> StValue .

    var st : StValue .
    var fld : Field$Elt .
    var val : StValue .
    var flds flds2 : NeList{Field} .

    eq find(val, nil) = val .
    eq find(storeSt(st, fld, val), fld flds) = find(val, flds) .

    eq find(st, flds flds2) = find(find(st, flds), flds2) .
endfm
