name: Maude
run-name: ${{ github.actor }} is running Maude in GitHub Actions 🚀
on: [push]
jobs:
  run-maude:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install Maude
          uses: ConorMacBride/install-package@v1
          with:
            apt: maude
        - name: Use Maude
          run: maude full-maude.maude